
trigger:
  batch: true  #when a pipeline is running, the system waits until the run is completed, then starts another run with all changes
  branches:
    include:
    - pipelines
  paths:
    include:
    - pipelines
    exclude:
    - Untrig

resources:
- repo: self

pool: CentOS
#  vmImage: 'ubuntu-latest'

parameters:
  - name: VarParametrsString
    displayName: 'Type of build  VarParametrsString'
    type: string
    default: 'type3'
    values: ['type1', 'type2', 'type3']

  - name: VarParametrsNumberA
    displayName: 'Type of build  VarParametrsNumber'
    type: number
    value: "10"

  - name: VarParametrsBooleanB
    displayName: 'Type of build  VarParametrsBoolean'
    type: boolean
    value: true 

variables:
  app: 'app'
  BRANCH: 'itea'
  poolvar: CentOS
  ACRvar: 'ksidopsaks'
  imagerRepo: '$(BRANCH)-$(app)'
  tag: '$(Build.BuildId)'
  NameSpaceDeploy: 'develop'
  URKACR: '$(ACRvar).azurecr.io'
  ACRurlVar: "$(ACRvar).azurecr.io/$(imagerRepo)"

stages:
##################################################
- stage: Stage1
  variables:
  - group: buildsENV
  displayName: DN-Stage1
  jobs:
  - job: Job1
    displayName: DN-Job1
    pool: $(poolvar)
    steps:
      - task: Bash@3
        displayName: DN-task1-showVariables
        inputs:
          targetType: 'inline'
          script: |
            echo "------show secret__variable from Library Var Group buildsENV------------------"

